mysql: &mysql
  adapter: mysql2
  username: root
  password:
  database: store_two_<%= Rails.env %>

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *mysql

test:
  <<: *defaults
  
development:
  <<: *defaults